name: Pressure Test

on:
  push:
    branches:
      - main  # 修改为你的默认分支

jobs:
  pressure-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.0  # 修改为你想要使用的 Go 版本

    - name: Go to pressure test directory
      run: cd path/to/your/pressure/test/script  # 将路径修改为你的压力测试脚本所在的目录

    - name: Build and install hey
      run: go install github.com/rakyll/hey@latest

    - name: Run pressure test
      run: hey -n 1000 -c 50 http://114.115.147.61:9097  # 根据你的需求修改压力测试参数和目标 IP、端口
